import { JetBrains_Mono } from "next/font/google";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import {ReactLenis} from "@/utils/lenis"



const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});
const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jetBrainsMono.variable} ${publicSans.variable} h-full antialiased`}
    >
      <ReactLenis root>
      <body className="min-h-full flex flex-col">{children}</body>
      </ReactLenis>
    </html>
  );
}
